I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\Пользователь\\Desktop\\OPD_novell\\NovelURFU\\game\\saves\\navigation.json.new' -> 'C:\\Users\\Пользователь\\Desktop\\OPD_novell\\NovelURFU\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\main.py", line 599, in main
    renpy.dump.dump(False)
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\Пользователь\\Desktop\\OPD_novell\\NovelURFU\\game\\saves\\navigation.json.new' -> 'C:\\Users\\Пользователь\\Desktop\\OPD_novell\\NovelURFU\\game\\saves\\navigation.json'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Путь в неизвестность 1.0
Sun Nov 24 19:30:04 2024
